//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnockBusterMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genre
    {
        public int GenreID { get; set; }
        public string Category { get; set; }
        public Nullable<int> MovieID { get; set; }
    
        public virtual Movy Movy { get; set; }
    }
}
